### ISSUE TITLE
ADL VS Tools freezes up computer over time

### ISSUE THREAD

**Issue by conniey** [Azure/usql#68] opened 2017-01-19 22:45 UTC
**Issue**

I have a VS solution with a couple of libraries and a U-SQL project.  After trying to compile my U-SQL scripts a few times, I am noticing that I regularly get compilation timeouts locally for queries that used to work.  Even when I am just editing code, I notice that there are lingering 'cl.exe's and 'conhost.exe's taking up my memory and CPU, which makes it impossible to code or do anything with my computer.  

In the image below, I am trying to rebuild my .NET 4.5 C# library (Microsoft.Fx.Portability.DataLake) but I can't because my CPU and resources are being consumed by these other processes.

![issue](https://cloud.githubusercontent.com/assets/10136526/22128043/9976b0de-de53-11e6-8f8e-3e04aaa98230.png)

**Repro**
1. Create U-SQL project, copy script under "SQL.MAP" section from https://msdn.microsoft.com/en-us/library/azure/mt764126.aspx (pasted below)
2. Open Task Manager
3. Right-click in Solution Explorer and select "Build"
4. Notice how cl.exe launches and so does conhost.exe
5. Wait for it to finish building, and it shows the vertex graph, etc.
6. Notice how conhost.exe is still there and takes up 24% CPU even though nothing is happening.

**Repro2**

To get all of those lingering cl.exes:

1. "Build all scripts" in my U-SQL project.  (I can share the solution file if you can't get it to reproduce.)
2. Have a script out of those 5 or 6 that fails building.
3. Wait for it to fail with errors or timeout on one.
4. Notice how VS says it is "Ready" in the taskbar, but the Task Manager has 'cl.exe's still there and processing.. something.
5. Even after closing VS, the 10+ cl.exe and conhost.exe are still running!

**Visual Studio Information**

Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02020

Installed Version: Enterprise

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

**Comment by yangyud-cn** [comment] 2017-03-01 02:55
Conniey,
I'm not able to reproduce this issue locally.  Could you please share the project with me ?

**Comment by MikeRys** [comment] 2017-04-19 20:21
Since there has not been any traffic on this issue, I assume it got addressed and am closing it. Please feel free to reopen if you need to follow up.

**Closed by MikeRys** 2017-04-19 20:21 UTC
