### ISSUE TITLE
VS crashes when registering an assembly larger than 15KB

### ISSUE THREAD

**Issue by conniey** [Azure/usql#69] opened 2017-01-19 23:04 UTC
**Repro Steps**
1. Open Cloud Explorer
2. Select Azure Subscription and expand Data Lake Analytics node, select an ADLA resource.
3. Expand Databases node, select a database
4. Right-click on "Assemblies" -> Register Assembly
5. Select "Load Assembly from Path" and choose a local assembly that is larger than 15KB, so you get the dialog:
```
Register assemblies larger than 15KB requires an Azure Data Lake Store location for temporary file storage. Click YES to choose the generated path adl://.../AssemblyCache_3f7b129b-8ad2-4c49-8ad7-dac13bc5b74f. Click NO to select another path.
```
6.  Select YES.

**Expected:** 

VS does not crash.  It does not crash when I perform this action locally.

**Actual:**

[Window Title]
Microsoft Visual Studio 2015
Microsoft Visual Studio 2015 has stopped working
Windows is collecting more information about the problem.  This might take several minutes...

**VS Information**
Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02020

Installed Version: Enterprise

ASP.NET and Web Tools 2015.1   14.1.20907.0
ASP.NET and Web Tools 2015.1

Azure App Service Tools v2.9.5   14.0.20810.0
Azure App Service Tools v2.9.5

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Hive Query Language Service   2.2.5000.0
Language service for Hive query

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40923.2

Microsoft Azure Tools   2.8
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.40211.

**Comment by yangyud-cn** [comment] 2017-03-01 02:47
Conniey,
Thanks for reporting this issue. But I couldn't reproduce it.  Could you please help to get two log files just after this happened and before restarting VS?  Just the latest one of the following log files.

C:\Users\__YOUR_ACCOUNT__\AppData\Roaming\Microsoft\DataLake\log\DataLake_*.svclog   and diagnostic_*.svclog

**Comment by conniey** [comment] 2017-03-01 05:48
Here are those files you asked for. I believe 20372 was just before it crashed... and 12216 was after VS automatically restarted itself.
[log.zip](https://github.com/Azure/usql/files/809791/log.zip)

**Comment by luw315** [comment] 2017-03-14 07:05
Conniey,
Thanks for reporting the issue. I can reproduce it. It will be fixed in the next version.

**Comment by MikeRys** [comment] 2017-04-19 20:19
I am closing this issue for now. If you still get the error with the current version, please reopen it.

**Closed by MikeRys** 2017-04-19 20:19 UTC
